CREATE TABLE `USER_INFO` (
  `USER_ID`  int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID' ,
  `USER_NAME`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '用户姓名' ,
  `USER_BIRTH`  date NULL DEFAULT NULL COMMENT '用户生日' ,
  PRIMARY KEY (`USER_ID`)
)
  ENGINE=InnoDB
  DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
  AUTO_INCREMENT=4
  ROW_FORMAT=DYNAMIC;

INSERT INTO `USER_INFO` (`USER_NAME`, `USER_BIRTH`) VALUES ('first', '1980-01-01');
INSERT INTO `USER_INFO` (`USER_NAME`, `USER_BIRTH`) VALUES ('second', '1990-01-01');
INSERT INTO `USER_INFO` (`USER_NAME`, `USER_BIRTH`) VALUES ('third', '2000-01-01');