logging:
  level:
    root: info

spring:
  data:
    mongodb:
      master:
        host:
          - 10.3.50.221
          - 10.3.50.221
          - 10.3.50.221
        port: 27221
        database: slave
        username: bigdata
        password: bigdata&2018
      slave:
        host: 10.3.50.221
        port: 27221
        database: slave
        username: bigdata
        password: bigdata&2018

swagger:
  enable: false